package net.brixian.unorganizeddeco.registry;

import net.brixian.unorganizeddeco.UnorganizedDeco;
import net.fabricmc.fabric.api.creativetab.v1.FabricCreativeModeTab;
import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.Identifier;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.ItemStack;

public class UDecoCreativeTab {
    public static final CreativeModeTab UD_DECO_TAB = Registry.register(BuiltInRegistries.CREATIVE_MODE_TAB,
            Identifier.fromNamespaceAndPath(UnorganizedDeco.MOD_ID, "enderscapes_delight_items"),
            FabricCreativeModeTab.builder().icon(() -> new ItemStack(UDecoBlocks.POLISHED_STONE))
                    .title(Component.translatable("itemgroup.enderscapes-delight.enderscapes_delight_items"))
                    .displayItems((parameters, output) -> {
                        output.accept(UDecoBlocks.POLISHED_STONE);
                        output.accept(UDecoBlocks.POLISHED_STONE_STAIRS);
                        output.accept(UDecoBlocks.POLISHED_STONE_SLAB);
                        output.accept(UDecoBlocks.POLISHED_STONE_WALL);
                        output.accept(UDecoBlocks.STONE_TILES);
                        output.accept(UDecoBlocks.STONE_TILES_STAIR);
                        output.accept(UDecoBlocks.STONE_TILES_SLAB);
                        output.accept(UDecoBlocks.STONE_TILES_WALL);
                        output.accept(UDecoBlocks.STONE_PILLAR);
                        output.accept(UDecoBlocks.POLISHED_GRANITE_WALL);
                        output.accept(UDecoBlocks.CHISELED_GRANITE);
                        output.accept(UDecoBlocks.GRANITE_BRICKS);
                        output.accept(UDecoBlocks.GRANITE_BRICK_STAIRS);
                        output.accept(UDecoBlocks.GRANITE_BRICK_SLAB);
                        output.accept(UDecoBlocks.GRANITE_BRICK_WALL);
                        output.accept(UDecoBlocks.GRANITE_TILES);
                        output.accept(UDecoBlocks.GRANITE_TILES_STAIRS);
                        output.accept(UDecoBlocks.GRANITE_TILES_SLAB);
                        output.accept(UDecoBlocks.GRANITE_TILES_WALL);
                        output.accept(UDecoBlocks.GRANITE_PILLAR);
                        output.accept(UDecoBlocks.POLISHED_DIORITE_WALL);
                        output.accept(UDecoBlocks.CHISELED_DIORITE);
                        output.accept(UDecoBlocks.DIORITE_BRICKS);
                        output.accept(UDecoBlocks.DIORITE_BRICK_STAIRS);
                        output.accept(UDecoBlocks.DIORITE_BRICK_SLAB);
                        output.accept(UDecoBlocks.DIORITE_BRICK_WALL);
                        output.accept(UDecoBlocks.DIORITE_TILES);
                        output.accept(UDecoBlocks.DIORITE_TILES_STAIRS);
                        output.accept(UDecoBlocks.DIORITE_TILES_SLAB);
                        output.accept(UDecoBlocks.DIORITE_TILES_WALL);
                        output.accept(UDecoBlocks.DIORITE_PILLAR);
                        output.accept(UDecoBlocks.POLISHED_ANDESITE_WALL);
                        output.accept(UDecoBlocks.CHISELED_ANDESITE);
                        output.accept(UDecoBlocks.ANDESITE_BRICKS);
                        output.accept(UDecoBlocks.ANDESITE_BRICK_STAIRS);
                        output.accept(UDecoBlocks.ANDESITE_BRICK_SLAB);
                        output.accept(UDecoBlocks.ANDESITE_BRICK_WALL);
                        output.accept(UDecoBlocks.ANDESITE_TILES);
                        output.accept(UDecoBlocks.ANDESITE_TILES_STAIRS);
                        output.accept(UDecoBlocks.ANDESITE_TILES_SLAB);
                        output.accept(UDecoBlocks.ANDESITE_TILES_WALL);
                        output.accept(UDecoBlocks.ANDESITE_PILLAR);
                        output.accept(UDecoBlocks.DEEPSLATE_PILLAR);
                        output.accept(UDecoBlocks.TUFF_TILES);
                        output.accept(UDecoBlocks.TUFF_TILES_STAIRS);
                        output.accept(UDecoBlocks.TUFF_TILES_SLAB);
                        output.accept(UDecoBlocks.TUFF_TILES_WALL);
                        output.accept(UDecoBlocks.TUFF_PILLAR);
                        output.accept(UDecoBlocks.CINNABAR_TILES);
                        output.accept(UDecoBlocks.CINNABAR_TILES_STAIRS);
                        output.accept(UDecoBlocks.CINNABAR_TILES_SLAB);
                        output.accept(UDecoBlocks.CINNABAR_TILES_WALL);
                        output.accept(UDecoBlocks.CINNABAR_PILLAR);
                        output.accept(UDecoBlocks.SULFUR_TILES);
                        output.accept(UDecoBlocks.SULFUR_TILES_STAIRS);
                        output.accept(UDecoBlocks.SULFUR_TILES_SLAB);
                        output.accept(UDecoBlocks.SULFUR_TILES_WALL);
                        output.accept(UDecoBlocks.SULFUR_PILLAR);
                        output.accept(UDecoBlocks.CHISELED_PRISMARINE);
                        output.accept(UDecoBlocks.POLISHED_PRISMARINE);
                        output.accept(UDecoBlocks.POLISHED_PRISMARINE_STAIRS);
                        output.accept(UDecoBlocks.POLISHED_PRISMARINE_SLAB);
                        output.accept(UDecoBlocks.POLISHED_PRISMARINE_WALL);
                        output.accept(UDecoBlocks.PRISMARINE_BRICK_WALL);
                        output.accept(UDecoBlocks.PRISMARINE_TILES);
                        output.accept(UDecoBlocks.PRISMARINE_TILES_STAIRS);
                        output.accept(UDecoBlocks.PRISMARINE_TILES_SLAB);
                        output.accept(UDecoBlocks.PRISMARINE_TILES_WALL);
                        output.accept(UDecoBlocks.PRISMARINE_PILLAR);
                        output.accept(UDecoBlocks.NETHERRACK_STAIRS);
                        output.accept(UDecoBlocks.NETHERRACK_SLAB);
                        output.accept(UDecoBlocks.NETHERRACK_WALL);
                        output.accept(UDecoBlocks.CHISELED_NETHERRACK);
                        output.accept(UDecoBlocks.POLISHED_NETHERRACK);
                        output.accept(UDecoBlocks.POLISHED_NETHERRACK_STAIRS);
                        output.accept(UDecoBlocks.POLISHED_NETHERRACK_SLAB);
                        output.accept(UDecoBlocks.POLISHED_NETHERRACK_WALL);
                        output.accept(UDecoBlocks.NETHERRACK_BRICKS);
                        output.accept(UDecoBlocks.NETHERRACK_BRICK_STAIRS);
                        output.accept(UDecoBlocks.NETHERRACK_BRICK_SLAB);
                        output.accept(UDecoBlocks.NETHERRACK_BRICK_WALL);
                        output.accept(UDecoBlocks.NETHERRACKS_TILES);
                        output.accept(UDecoBlocks.NETHERRACK_TILES_STAIRS);
                        output.accept(UDecoBlocks.NETHERRACK_TILES_SLAB);
                        output.accept(UDecoBlocks.NETHERRACK_TILES_WALL);
                        output.accept(UDecoBlocks.NETHERRACK_PILLAR);
                        output.accept(UDecoBlocks.CHISELED_BASALT);
                        output.accept(UDecoBlocks.BASALT_BRICKS);
                        output.accept(UDecoBlocks.BASALT_BRICK_STAIRS);
                        output.accept(UDecoBlocks.BASALT_BRICK_SLAB);
                        output.accept(UDecoBlocks.BASALT_BRICK_WALL);
                        output.accept(UDecoBlocks.BASALT_TILES);
                        output.accept(UDecoBlocks.BASALT_TILES_STAIRS);
                        output.accept(UDecoBlocks.BASALT_TILES_SLAB);
                        output.accept(UDecoBlocks.BASALT_TILES_WALL);
                        output.accept(UDecoBlocks.BASALT_PILLAR);
                        output.accept(UDecoBlocks.SMOOTH_BASALT_STAIRS);
                        output.accept(UDecoBlocks.SMOOTH_BASALT_SLAB);
                        output.accept(UDecoBlocks.BLACKSTONE_TILES);
                        output.accept(UDecoBlocks.BLACKSTONE_TILES_STAIRS);
                        output.accept(UDecoBlocks.BLACKSTONE_TILES_SLAB);
                        output.accept(UDecoBlocks.BLACKSTONE_TILES_WALL);
                        output.accept(UDecoBlocks.BLACKSTONE_PILLAR);
                        output.accept(UDecoBlocks.END_STONE_STAIRS);
                        output.accept(UDecoBlocks.END_STONE_SLAB);
                        output.accept(UDecoBlocks.END_STONE_WALL);
                        output.accept(UDecoBlocks.CHISELED_END_STONE);
                        output.accept(UDecoBlocks.POLISHED_END_STONE);
                        output.accept(UDecoBlocks.POLISHED_END_STONE_STAIRS);
                        output.accept(UDecoBlocks.POLISHED_END_STONE_SLAB);
                        output.accept(UDecoBlocks.POLISHED_END_STONE_WALL);
                        output.accept(UDecoBlocks.END_STONE_TILES);
                        output.accept(UDecoBlocks.END_STONE_TILES_STAIRS);
                        output.accept(UDecoBlocks.END_STONE_TILES_SLAB);
                        output.accept(UDecoBlocks.END_STONE_TILES_WALL);
                        output.accept(UDecoBlocks.END_STONE_PILLAR);
                        output.accept(UDecoBlocks.LAPIS_STAIRS);
                        output.accept(UDecoBlocks.LAPIS_SLAB);
                        output.accept(UDecoBlocks.CHISELED_LAPIS);
                        output.accept(UDecoBlocks.LAPIS_BRICKS);
                        output.accept(UDecoBlocks.LAPIS_BRICK_STAIRS);
                        output.accept(UDecoBlocks.LAPIS_BRICK_SLAB);
                        output.accept(UDecoBlocks.LAPIS_TILES);
                        output.accept(UDecoBlocks.LAPIS_TILES_STAIRS);
                        output.accept(UDecoBlocks.LAPIS_TILES_SLAB);
                        output.accept(UDecoBlocks.LAPIS_TILES_WALL);
                        output.accept(UDecoBlocks.LAPIS_PILLAR);
                        output.accept(UDecoBlocks.SMOOTH_LAPIS);
                        output.accept(UDecoBlocks.SMOOTH_LAPIS_STAIRS);
                        output.accept(UDecoBlocks.SMOOTH_LAPIS_SLAB);
                        output.accept(UDecoBlocks.QUARTZ_BRICK_STAIRS);
                        output.accept(UDecoBlocks.QUARTZ_BRICK_SLAB);
                        output.accept(UDecoBlocks.QUARTZ_BRICK_WALL);
                        output.accept(UDecoBlocks.QUARTZ_TILES);
                        output.accept(UDecoBlocks.QUARTZ_TILES_STAIRS);
                        output.accept(UDecoBlocks.QUARTZ_TILES_SLAB);
                        output.accept(UDecoBlocks.QUARTZ_TILES_WALL);
                        output.accept(UDecoBlocks.CALCITE_STAIRS);
                        output.accept(UDecoBlocks.CALCITE_SLAB);
                        output.accept(UDecoBlocks.CALCITE_WALL);
                        output.accept(UDecoBlocks.CHISELED_CALCITE);
                        output.accept(UDecoBlocks.POLISHED_CALCITE);
                        output.accept(UDecoBlocks.POLISHED_CALCITE_STAIRS);
                        output.accept(UDecoBlocks.POLISHED_CALCITE_SLAB);
                        output.accept(UDecoBlocks.POLISHED_CALCITE_WALL);
                        output.accept(UDecoBlocks.CALCITE_BRICKS);
                        output.accept(UDecoBlocks.CALCITE_BRICK_STAIRS);
                        output.accept(UDecoBlocks.CALCITE_BRICK_SLAB);
                        output.accept(UDecoBlocks.CALCITE_BRICK_WALL);
                        output.accept(UDecoBlocks.CALCITE_TILES);
                        output.accept(UDecoBlocks.CALCITE_TILES_STAIRS);
                        output.accept(UDecoBlocks.CALCITE_TILES_SLAB);
                        output.accept(UDecoBlocks.CALCITE_TILES_WALL);
                        output.accept(UDecoBlocks.CALCITE_PILLAR);
                        output.accept(UDecoBlocks.POLISHED_STONE);
                        output.accept(UDecoBlocks.POLISHED_STONE);
                        output.accept(UDecoBlocks.POLISHED_STONE);
                        output.accept(UDecoBlocks.POLISHED_STONE);
                        output.accept(UDecoBlocks.POLISHED_STONE);
                        output.accept(UDecoBlocks.POLISHED_STONE);
                        output.accept(UDecoBlocks.POLISHED_STONE);
                        output.accept(UDecoBlocks.POLISHED_STONE);
                        output.accept(UDecoBlocks.POLISHED_STONE);
                        output.accept(UDecoBlocks.POLISHED_STONE);
                        output.accept(UDecoBlocks.POLISHED_STONE);
                        output.accept(UDecoBlocks.POLISHED_STONE);
                        output.accept(UDecoBlocks.POLISHED_STONE);
                        output.accept(UDecoBlocks.POLISHED_STONE);
                        output.accept(UDecoBlocks.POLISHED_STONE);
                        output.accept(UDecoBlocks.POLISHED_STONE);
                        output.accept(UDecoBlocks.POLISHED_STONE);
                        output.accept(UDecoBlocks.POLISHED_STONE);
                        output.accept(UDecoBlocks.POLISHED_STONE);
                        output.accept(UDecoBlocks.POLISHED_STONE);
                        output.accept(UDecoBlocks.POLISHED_STONE);
                        output.accept(UDecoBlocks.POLISHED_STONE);
                        output.accept(UDecoBlocks.POLISHED_STONE);
                        output.accept(UDecoBlocks.POLISHED_STONE);
                        output.accept(UDecoBlocks.POLISHED_STONE);
                        output.accept(UDecoBlocks.POLISHED_STONE);
                        output.accept(UDecoBlocks.POLISHED_STONE);
                        output.accept(UDecoBlocks.POLISHED_STONE);
                        output.accept(UDecoBlocks.POLISHED_STONE);
                        output.accept(UDecoBlocks.POLISHED_STONE);





                    }).build());

    public static void registerEDModCreativeModeTabs() {
        UnorganizedDeco.LOGGER.info("Registering Creative Mode Tabs for " + UnorganizedDeco.MOD_ID);
    }
}
